envs:
  global:
    variables:
      tapir: dingo
      TRIGGER_REFSPEC: +refs/heads/master:refs/remotes/origin/master

flows:
  master:
    job: anders-dummy-project
  pr:
    job: anders-dummy-project
