envs:
  global:
    variables:
      tapir: dingo
      TRIGGER_BRANCH: master
      TRIGGER_REFSPEC: +refs/heads/master:refs/remotes/origin/master
      GITHUB_PR_SOURCE_BRANCH: a-dummy-branch # ${GITHUB_PR_SOURCE_BRANCH}

flows:
  master:
    job: anders-dummy-project
  pr:
    job: anders-dummy-project
